// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: key.proto

package key

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Extension int32

const (
	Extension_jpg Extension = 0
	Extension_png Extension = 1
	Extension_gif Extension = 3
	Extension_mov Extension = 4
	Extension_mp4 Extension = 5
)

// Enum value maps for Extension.
var (
	Extension_name = map[int32]string{
		0: "jpg",
		1: "png",
		3: "gif",
		4: "mov",
		5: "mp4",
	}
	Extension_value = map[string]int32{
		"jpg": 0,
		"png": 1,
		"gif": 3,
		"mov": 4,
		"mp4": 5,
	}
)

func (x Extension) Enum() *Extension {
	p := new(Extension)
	*p = x
	return p
}

func (x Extension) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Extension) Descriptor() protoreflect.EnumDescriptor {
	return file_key_proto_enumTypes[0].Descriptor()
}

func (Extension) Type() protoreflect.EnumType {
	return &file_key_proto_enumTypes[0]
}

func (x Extension) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Extension.Descriptor instead.
func (Extension) EnumDescriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{0}
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          *uint64                `protobuf:"varint,1,opt,name=hash" json:"hash,omitempty"`
	Extension     *Extension             `protobuf:"varint,2,opt,name=extension,enum=Extension" json:"extension,omitempty"`
	Size          *uint32                `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetHash() uint64 {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return 0
}

func (x *Key) GetExtension() Extension {
	if x != nil && x.Extension != nil {
		return *x.Extension
	}
	return Extension_jpg
}

func (x *Key) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_key_proto protoreflect.FileDescriptor

const file_key_proto_rawDesc = "" +
	"\n" +
	"\tkey.proto\"W\n" +
	"\x03Key\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\x04R\x04hash\x12(\n" +
	"\textension\x18\x02 \x01(\x0e2\n" +
	".ExtensionR\textension\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size*8\n" +
	"\tExtension\x12\a\n" +
	"\x03jpg\x10\x00\x12\a\n" +
	"\x03png\x10\x01\x12\a\n" +
	"\x03gif\x10\x03\x12\a\n" +
	"\x03mov\x10\x04\x12\a\n" +
	"\x03mp4\x10\x05B+Z)github.com/leedo/imgur-at-edge/protos/keyb\beditionsp\xe8\a"

var (
	file_key_proto_rawDescOnce sync.Once
	file_key_proto_rawDescData []byte
)

func file_key_proto_rawDescGZIP() []byte {
	file_key_proto_rawDescOnce.Do(func() {
		file_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)))
	})
	return file_key_proto_rawDescData
}

var file_key_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_key_proto_goTypes = []any{
	(Extension)(0), // 0: Extension
	(*Key)(nil),    // 1: Key
}
var file_key_proto_depIdxs = []int32{
	0, // 0: Key.extension:type_name -> Extension
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_key_proto_init() }
func file_key_proto_init() {
	if File_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_key_proto_goTypes,
		DependencyIndexes: file_key_proto_depIdxs,
		EnumInfos:         file_key_proto_enumTypes,
		MessageInfos:      file_key_proto_msgTypes,
	}.Build()
	File_key_proto = out.File
	file_key_proto_goTypes = nil
	file_key_proto_depIdxs = nil
}
